apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: q71
spec:
  template:
    spec:
      containers:
      - name: nginx
        envFrom:
        - secretRef:
            name: creds