apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: database
spec:
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Never